# Generated by Django 4.0.1 on 2022-01-12 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_bankaccout_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccout',
            name='account_no',
            field=models.PositiveIntegerField(default=0, unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
