# Generated by Django 4.0.1 on 2022-01-12 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_alter_bankaccout_account_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccout',
            name='accNumber',
            field=models.AutoField(default=2, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccout',
            name='account_no',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
