# Generated by Django 4.0.1 on 2022-01-12 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_bankaccout_accnumber_alter_bankaccout_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccout',
            name='accNumber',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
