# Generated by Django 4.0.1 on 2022-01-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_alter_bankaccout_accnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccout',
            name='Referrence_Number',
            field=models.CharField(blank=True, default='4831754591', editable=False, max_length=10, unique=True),
        ),
    ]
