# Generated by Django 4.0.1 on 2022-01-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_bankaccout_referrence_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccout',
            name='Referrence_Number',
        ),
        migrations.RemoveField(
            model_name='bankaccout',
            name='account_no',
        ),
        migrations.AddField(
            model_name='bankaccout',
            name='waluts',
            field=models.CharField(choices=[('PL', 'Zł'), ('EUR', 'Euro'), ('USD', 'Dolar')], default='PL', max_length=3),
        ),
    ]
