# Generated by Django 4.0.1 on 2022-01-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_bankaccout_accname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccout',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccout',
            name='accNumber',
            field=models.IntegerField(),
        ),
    ]
