# Generated by Django 4.0.1 on 2022-01-13 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_bankaccout_id_alter_bankaccout_accnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('data', models.DateTimeField()),
                ('fromBank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromBank', to='bank.bankaccout')),
                ('toBank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toBank', to='bank.bankaccout')),
            ],
        ),
    ]
