# Generated by Django 4.0.1 on 2022-01-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0016_alter_bankaccout_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccout',
            options={'default_related_name': 'bankAccount'},
        ),
    ]
